# Generated by Django 5.0 on 2024-01-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
