# Generated by Django 5.0 on 2024-01-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='job_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
