# Generated by Django 5.0 on 2024-01-09 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0002_alter_attendanceuser_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='job_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
