# Generated by Django 5.0 on 2024-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0003_alter_attendanceuser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
