# Generated by Django 5.0 on 2024-01-09 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0004_alter_attendanceuser_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(blank=True, default=datetime.time(13, 45, 34, 189350), null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='start',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
