# Generated by Django 5.0 on 2024-01-09 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0005_alter_attendanceuser_end_alter_attendanceuser_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(blank=True, default=datetime.time(13, 45, 39, 57693), null=True),
        ),
    ]
