# Generated by Django 5.0 on 2024-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0007_alter_attendanceuser_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
