# Generated by Django 5.0 on 2024-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0009_alter_attendanceuser_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
