# Generated by Django 5.0 on 2024-01-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0010_alter_attendanceuser_end_alter_attendanceuser_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='job_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
